# Generated by Django 6.0.2 on 2026-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_fieldtestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtestmodel',
            name='nullable_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
