# Generated by Django 6.0.2 on 2026-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_fieldtestmodel_nullable_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkedge",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
